class OreDict:
    ARMOR = "mcpython:oredict:armor"
    ARMOR_HEAD = "mcpython:oredict:armor:head"
    ARMOR_BODY = "mcpython:oredict:armor:body"
    ARMOR_LEG = "mcpython:oredict:armor:leg"
    ARMOR_FOOT = "mcpython:oredict:armor:foot"

    TOOL_SHOVEL = "mcpython:oredict:tool:shovel"
    TOOL_PICKAXE = "mcpython:oredict:tool:pickaxe"
    TOOL_HOE = "mcpython:oredict:tool:hoe"
    TOOL_AXE = "mcpython:oredict:tool:axe"
    TOOL_SWORD = "mcpython:oredict:tool:sword"

    FUEL = "mcpython:oredict:fuel"

    DIRT = "mcpython:oredict:dirt"
    GRASS = "mcpython:oredict:grass"
    STONE = "mcpython:oredict:stone"
    WOOL = "mcpython:oredict:wool"
    WOOD_PLANK = "mcpython:oredict:wood_plank"
    WOOD_LOG = "mcpython:oredict:wood_log"
    ORE_DROP = "mcpython:oredict:oredrop"

    DYE = "mcpython:oredict:dye"
    WHITE_DYE = "mcpython:oredict:dye:white"
    BROWN_DYE = "mcpython:oredict:dye:brown"
    GREEN_DYE = "mcpython:oredict:dye:green"
    GREY_DYE = "mcpython:oredict:dye:grey"
    BLACK_DYE = "mcpython:oredict:dye:back_dye"
    BLUE_DYE = "mcpython:oredict:dye:blue"
    LIGHT_BLUE_DYE = "mcpython:oredict:dye:light_blue"
    LIGHT_GREEN_DYE = "mcpython:oredict:dye:light_green"
    LIGHT_LIGHT_BLUE_DYE = "mcpython:oredict:dye:light_light_blue"
    MAGENTA_DYE = "mcpython:oredict:dye:magenta"
    ORANGE_DYE = "mcpython:oredict:dye:orange"
    PINK_DYE = "mcpython:oredict:dye:pink"
    PURPEL_DYE = "mcpython:oredict:dye:purpel"
    RED_DYE = "mcpython:oredict:dye:red"
    YELLOW_DYE = "mcpython:oredict:dye:yellow"

    # minecraft oredict
    AcaciaLogs = "minecraft:acacia_logs"
    BirchLogs = "minecraft:birch_logs"
    DarkOakLogs = "minecraft:dark_oak_logs"
    JungleLogs = "minecraft:jungle_logs"
    OakLogs = "minecraft:oak_logs"
    SpruceLogs = "minecraft:spruce_logs"

    Coal = "minecraft:coal"
    QuartBlock = "minecraft:quarz_block"
    RedSandstone = "minecraft:red_sandstone"
